[db]
user = "colosseumdb_admin"
password = "pwd"
host = "localhost"
port = 5432
name = "colosseumdb"

[servers]

[servers.alpha]
url = "http://localhost:8001"
token = "password"

[files]
mb_limit = 10
